[tool.poetry]
name = "botnos"
version = "0.1.0"
description = ""
authors = ["khabar0v <alexander.khabarov.123@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
